// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPk3a7xFtt8W13fyMaepOGz6Gqz5mv6J0',
    appId: '1:305536776881:web:ba5c3d4fe140e210a20090',
    messagingSenderId: '305536776881',
    projectId: 'basic-app-c8775',
    authDomain: 'basic-app-c8775.firebaseapp.com',
    storageBucket: 'basic-app-c8775.appspot.com',
    measurementId: 'G-GLGLQDVLS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz_YPK_vMKYtrEisXSImGe8q8sJ9Y62vg',
    appId: '1:305536776881:android:a49e487681bf8805a20090',
    messagingSenderId: '305536776881',
    projectId: 'basic-app-c8775',
    storageBucket: 'basic-app-c8775.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB471ctz7Aqi0SYGUJyu5DIEnrt9WT-IL4',
    appId: '1:305536776881:ios:5c6c78991b6171e0a20090',
    messagingSenderId: '305536776881',
    projectId: 'basic-app-c8775',
    storageBucket: 'basic-app-c8775.appspot.com',
    iosClientId: '305536776881-bhrbv95r8o57744gncgnjpmkhvqumd8t.apps.googleusercontent.com',
    iosBundleId: 'com.example.basicApp',
  );
}
